### ISSUE TITLE
Relish Documentation fix

### ISSUE THREAD

**Issue by chaffeqa** [dchelimsky/rspec-rails#13]
Dont know where else to put this issue... 

on the relish.com site: [controller spec](https://www.relishapp.com/rspec/rspec-rails/docs/controller-specs) page, you write:

```
  response.code.should eq(200)
```

Where that would fail since `response.code` returns a String `"200"` and not an integer.  I dove into the source to see if it was a matcher issue, but it was the `.code`, which returns a String, what would make the above pass is:

```
 response.status.should eq(200)
```

No biggie, just a gotcha

**Comment by alindeman** [comment]
I'll get to this over on rspec/rspec-rails. This tracker is for rspec 1. @dchelimsky, want to close this one?

**Comment by dchelimsky** [comment]
Thx.
