### ISSUE TITLE
ActionDispatch::ClosedError: Cannot modify cookies because it was closed. This means it was already streamed back to the client or converted to HTTP headers.

### ISSUE THREAD

**Issue by dreamr** [dchelimsky/rspec-rails#3]
I logged it at rails 3.1 as well: https://github.com/rails/rails/issues/1452

So I think this has to do with the before vs streaming starting and cookies and sessions being closed now. Anywhere I call to create a model in a request spec in a before block this error shows up. It was showing up for me with flash messages to until there was a patch in edge rails to fix it: https://github.com/rails/rails/pull/290

This does not address the issue with cookies though. I am not sure if it is rspec or rails' issue so i'll let you guys work that out. I will tackle it this weekend to see which myself.

**Comment by dreamr** [comment]
this is edge rspec2 rails + edge rails 3.1

**Comment by dchelimsky** [comment]
This is the tracker for rspec-rails-1 - please repost to https://github.com/rspec/rspec-rails/issues.

Thx.
