### ISSUE TITLE
Rake 0.9.1 Deprecation Warnings...

### ISSUE THREAD

**Issue by MattRogish** [dchelimsky/rspec-rails#4]
When rake goes to parse lib/tasks/rspec.rake (in 1.3.2):

WARNING: Global access to Rake DSL methods is deprecated. Please Include Rake::DSL into classes and modules which use the Rake DSL methods. 
WARNING: DSL method Spec::Rake::SpecTask#task called at lib/tasks/rspec.rake:28:in `initialize'

to fix:
  module Spec
    module Rake
      class SpecTask
        # Start
        include ::Rake::DSL
        # end
        def initialize(name)

"include Rake::DSL" gets confused and looks in the Spec namespace's Rake, which doesn't have DSL, so you have to ::Rake...

**Comment by ngan** [comment]
This has been fixed :-)
https://github.com/dchelimsky/rspec-rails/pull/11

**Comment by dchelimsky** [comment]
Fixed by #11.
